import {HttpClient} from '@angular/common/http';
import {inject,Injectable} from '@angular/core';
import {HttpParams} from '@angular/common/http';
export type AssetDataType='STOCK'|'ETF'|'INDEX';
export interface RiskAdjustedMomentumAsset{stockName:string;oneYearReturn:number;sixMonthReturn:number;threeMonthReturn:number;volatility:number;qualifiesForMomentum:boolean;strategyRunDate:string;rank12Months?:number;rank6Months?:number;rank3Months?:number;totalRankScore?:number;stopLossLevel?:number;}
export type AllocationMode='EQUAL_WEIGHT'|'INVERSE_VOL';
export type StopModel='FIXED'|'TIERED'|'ATR';
export interface RiskAdjustedMomentumRegimeOverlay{benchmark:string;breadthPercent:number;benchmarkAboveSma:boolean;exposureCapPercent:number;newBuysAllowed:boolean;effectiveEntryRank:number;}
export interface RiskAdjustedMomentumResult{allStocks:RiskAdjustedMomentumAsset[];qualifiedStocks:RiskAdjustedMomentumAsset[];topStockNames:string[];retainedStockNames:string[];totalAnalyzed:number;qualifiedCount:number;valid:boolean;message:string;regimeOverlay?:RiskAdjustedMomentumRegimeOverlay;}
export interface RiskAdjustedMomentumExecution{assetDataType:AssetDataType;strategyRunDate:string;resultCount:number;analyzedCount:number;lastUpdatedAt:string|null;}
export interface SavedRiskAdjustedMomentumAsset{stockName:string;oneYearReturn:number;sixMonthReturn:number;threeMonthReturn:number;volatility:number;inverseVolWeight:number;strategyRunDate:string;rank12Months:number;rank6Months:number;rank3Months:number;totalRankScore:number;}
@Injectable({providedIn:'root'}) export class RiskAdjustedMomentumAnalysisService{private readonly http=inject(HttpClient);run(type:AssetDataType,asOfDate:string,entryRank:number,retentionRank:number,allocationMode:AllocationMode,benchmark:string,stopModel:StopModel,trailingStopPercent:number,atrPeriod:number,atrMultiplier:number,benchmarkSmaPeriod:number,breadthThresholdPercent:number,weakExposureCapPercent:number){const params=new HttpParams().set('asOfDate',asOfDate).set('entryRank',entryRank).set('retentionRank',retentionRank).set('allocationMode',allocationMode).set('benchmark',benchmark).set('stopModel',stopModel).set('trailingStopPercent',trailingStopPercent).set('atrPeriod',atrPeriod).set('atrMultiplier',atrMultiplier).set('benchmarkSmaPeriod',benchmarkSmaPeriod).set('breadthThresholdPercent',breadthThresholdPercent).set('weakExposureCapPercent',weakExposureCapPercent);return this.http.post<RiskAdjustedMomentumResult>(`/api/risk-adjusted-momentum/calculate-and-rank/${type}`,null,{params});}executions(type?:AssetDataType){const params=type?new HttpParams().set('assetDataType',type):undefined;return this.http.get<RiskAdjustedMomentumExecution[]>('/api/risk-adjusted-momentum/executions',{params});}savedResults(type:AssetDataType,date:string){return this.http.get<SavedRiskAdjustedMomentumAsset[]>(`/api/risk-adjusted-momentum/executions/${type}/${date}`);}}
