runtime: java21
instance_class: F4

automatic_scaling:
  max_instances: 2

entrypoint: java --enable-preview -jar target/*.jar

env_variables:
  SPRING_PROFILES_ACTIVE: prod

beta_settings:
  cloud_sql_instances: cultivated-pen-482514-m6:asia-south1:free-trial-first-project
