steps:
  - name: eclipse-temurin:21-jdk
    entrypoint: bash
    args:
      - -c
      - |
        ./mvnw clean package -DskipTests

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
