import {HttpClient,HttpParams} from '@angular/common/http';
import {inject,Injectable} from '@angular/core';
import {map} from 'rxjs';
import {NiftyIndexName} from '../nifty-index-stock/nifty-index-stock.service';
export interface MomentumBacktestRequest{startDate:string;endDate:string;initialCapital:number;entryRank:number;retentionRank:number;benchmark:string;niftyIndex:NiftyIndexName;transactionCostPercent:number;slippagePercent:number;riskFreeRatePercent:number;rebalanceMode:string;bufferAmount:number;maximumLeverageAmount:number;borrowingInterestRatePercent:number;}
export interface Decision{ticker:string;action:'KEEP'|'SELL'|'BUY'|'RESIZE_UP'|'RESIZE_DOWN';previousRank:number|null;currentRank:number;rank12:number;rank6:number;rank3:number;totalRank:number;originalEntryDate:string|null;executionPrice:number;quantity:number;realizedProfitLoss:number|null;}
export interface Rebalance{signalDate:string;executionDate:string;portfolioValue:number;benchmarkValue:number;cash:number;turnoverPercent:number;costs:number;decisions:Decision[];}
export interface Position{ticker:string;totalRank:number;quantity:number;entryPrice:number;currentPrice:number;marketValue:number;profitLoss:number;weightPercent:number;}
export interface YearlyPerformance{year:number;portfolioReturn:number;benchmarkReturn:number;excessReturn:number;maximumDrawdown:number;turnoverPercent:number;costs:number;monthlyWinRate:number;}
export interface RollingPerformance{endDate:string;months:number;portfolioReturn:number;benchmarkReturn:number;excessReturn:number;maximumDrawdown:number;annualizedVolatility:number;}
export interface WinnerContribution{ticker:string;realizedProfitLoss:number;unrealizedProfitLoss:number;totalContribution:number;contributionPercentOfNetProfit:number;}
export interface ParameterStability{entryRank:number;retentionRank:number;totalReturn:number;cagr:number;maximumDrawdown:number;sharpeRatio:number;turnoverPercent:number;totalCosts:number;}
export interface WalkForwardWindow{trainingStart:string;trainingEnd:string;testStart:string;testEnd:string;selectedEntryRank:number;selectedRetentionRank:number;trainingSharpeRatio:number;testReturn:number;testCagr:number;testMaximumDrawdown:number;testSharpeRatio:number;benchmarkTestReturn:number;testExcessReturn:number;}
export interface MomentumBacktestExecutionSummary{id:string;createdAt:string;startDate:string;endDate:string;entryRank:number;retentionRank:number;benchmark:string;rebalanceMode:string;finalValue:number;totalReturn:number;cagr:number;maximumDrawdown:number;sharpeRatio:number;}
export interface MomentumBacktestResult{startDate:string;endDate:string;initialCapital:number;finalValue:number;totalReturn:number;cagr:number;maximumDrawdown:number;benchmark:string;benchmarkFinalValue:number;benchmarkReturn:number;benchmarkCagr:number;benchmarkMaximumDrawdown:number;annualizedVolatility:number;sharpeRatio:number;sortinoRatio:number;calmarRatio:number;monthlyWinRate:number;benchmarkOutperformanceRate:number;riskFreeRatePercent:number;rebalanceMode:string;bufferAmount:number;maximumLeverageAmount:number;borrowingInterestRatePercent:number;maximumBufferUsed:number;maximumBorrowed:number;borrowingInterestPaid:number;lowestCashBalance:number;excessReturn:number;rebalanceCount:number;tradeCount:number;totalCosts:number;equityCurve:{date:string;portfolioValue:number;benchmarkValue:number;drawdown:number}[];finalPositions:Position[];rebalances:Rebalance[];yearlyPerformance:YearlyPerformance[];rollingPerformance:RollingPerformance[];winnerContributions:WinnerContribution[];parameterStability:ParameterStability[];walkForwardWindows:WalkForwardWindow[];}
@Injectable({providedIn:'root'}) export class MomentumBacktestService{private readonly http=inject(HttpClient);run(request:MomentumBacktestRequest){return this.http.post<MomentumBacktestResult>('/api/momentum-backtest/run/stock',null,{params:this.params(request),observe:'response'}).pipe(map(response=>({result:response.body!,runId:response.headers.get('X-Backtest-Run-Id')})));}history(){return this.http.get<MomentumBacktestExecutionSummary[]>('/api/momentum-backtest/executions');}execution(runId:string){return this.http.get<MomentumBacktestResult>(`/api/momentum-backtest/executions/${runId}`);}exportExecution(runId:string){return this.http.get(`/api/momentum-backtest/export/${runId}`,{responseType:'blob'});}export(request:MomentumBacktestRequest){return this.http.post('/api/momentum-backtest/export/stock',null,{params:this.params(request),responseType:'blob'});}private params(request:MomentumBacktestRequest){let params=new HttpParams();Object.entries(request).forEach(([key,value])=>params=params.set(key,String(value)));return params;}}
