-- No default users or passwords. The server initializes one random shared signing key.
CREATE TABLE IF NOT EXISTS app_signing_key (
    key_id varchar(32) PRIMARY KEY,
    secret_base64 varchar(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS app_user_account (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL UNIQUE,
    password_hash varchar(100) NOT NULL,
    role varchar(10) NOT NULL CHECK (role IN ('SUPERADMIN', 'ADMIN', 'USER')),
    enabled boolean NOT NULL DEFAULT true,
    token_version bigint NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT app_user_account_normalized_email CHECK (email = lower(trim(email)))
);
