package org.factor_investing.quant_strategy.model;

public enum BreadthAlertType {
    BREADTH_50D_CROSS_50_UP,
    BREADTH_50D_CROSS_50_DOWN,
    BREADTH_50D_CROSS_60_UP,
    BREADTH_50D_CROSS_60_DOWN,
    BREADTH_50D_CROSS_70_UP,
    BREADTH_50D_CROSS_70_DOWN,
    BREADTH_200D_CROSS_UP,
    BREADTH_200D_CROSS_DOWN,
    BEARISH_AD_DIVERGENCE,
    ZWEIG_BREADTH_THRUST,
    MCCLELLAN_ZERO_CROSS_UP,
    MCCLELLAN_ZERO_CROSS_DOWN,
    SUMMATION_TREND_FLIP_UP,
    SUMMATION_TREND_FLIP_DOWN,
    NET_NEW_HIGHS_NEGATIVE_FLIP,
    SECTOR_BREADTH_NARROWING,
    INDIA_VIX_SPIKE,
    INDIA_VIX_CROSS_ABOVE_EMA,
    INDIA_VIX_CROSS_BELOW_EMA
}
