import {Component,OnInit,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Paginator,PaginatorState} from '@openng/optimus-ui/paginator';
import {finalize} from 'rxjs';
import {ETFMaster,ETFMasterPayload,ETFMasterService} from './etf-master.service';
@Component({selector:'app-etf-master',imports:[FormsModule,Paginator],templateUrl:'./etf-master.component.html',styleUrl:'./etf-master.component.scss'})
export class ETFMasterComponent implements OnInit {
 private readonly service=inject(ETFMasterService); readonly etfs=signal<ETFMaster[]>([]);readonly loading=signal(false);readonly saving=signal(false);readonly importing=signal(false);readonly formOpen=signal(false);readonly editingId=signal<number|null>(null);readonly message=signal<{kind:'success'|'error';text:string}|null>(null);readonly first=signal(0);readonly rows=signal(10);readonly pagedETFs=computed(()=>this.etfs().slice(this.first(),this.first()+this.rows()));readonly rowsPerPageOptions=[10,20,50];search='';form:ETFMasterPayload=this.empty();
 ngOnInit(){this.load();} load(){this.loading.set(true);this.service.list(this.search).pipe(finalize(()=>this.loading.set(false))).subscribe({next:data=>{this.etfs.set(data);this.first.set(0)},error:()=>this.error('ETF records could not be loaded. Make sure Spring Boot is running.')});}
 openCreate(){this.editingId.set(null);this.form=this.empty();this.formOpen.set(true);this.message.set(null);} openEdit(etf:ETFMaster){this.editingId.set(etf.id);this.form={symbol:etf.symbol,underlying:etf.underlying,securityName:etf.securityName,dateOfListing:etf.dateOfListing,marketLot:etf.marketLot,isinNumber:etf.isinNumber,faceValue:etf.faceValue};this.formOpen.set(true);this.message.set(null);} closeForm(){this.formOpen.set(false);}
 save(){const id=this.editingId();const operation=id===null?this.service.create(this.form):this.service.update(id,this.form);this.saving.set(true);operation.pipe(finalize(()=>this.saving.set(false))).subscribe({next:etf=>{this.formOpen.set(false);this.message.set({kind:'success',text:`${etf.symbol} was ${id===null?'added':'updated'} successfully.`});this.load();},error:e=>this.error(e?.error?.message||'The ETF could not be saved.')});}
 remove(etf:ETFMaster){if(!window.confirm(`Delete ${etf.symbol} from ETF Master?`))return;this.service.delete(etf.id).subscribe({next:()=>{this.message.set({kind:'success',text:`${etf.symbol} was deleted successfully.`});this.load();},error:e=>this.error(e?.error?.message||'The ETF could not be deleted.')});}
 pageChanged(e:PaginatorState){this.first.set(e.first??0);this.rows.set(e.rows??10);}
  selectCsv(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];input.value='';if(!file)return;if(!file.name.toLowerCase().endsWith('.csv')){this.error('Please select a CSV file.');return;}const reader=new FileReader();reader.onload=()=>{const header=String(reader.result??'').replace(/^\uFEFF/,'').split(/\r?\n/,1)[0].split(',').map(v=>v.trim()).join(',');const expected='Symbol,Underlying,SecurityName,DateofListing,MarketLot,ISINNumber,FaceValue';if(header!==expected){this.error(`Invalid columns. Expected exactly: ${expected}`);return;}if(!window.confirm('Replace the complete ETF Master list with this CSV? ETFs absent from the file will be removed when they are not referenced by price history.'))return;this.importing.set(true);this.service.importCsv(file).pipe(finalize(()=>this.importing.set(false))).subscribe({next:r=>{this.message.set({kind:'success',text:`CSV uploaded: ${r.totalRecords} total, ${r.created} added, ${r.updated} updated and ${r.removed} removed.`});this.search='';this.load();},error:e=>this.error(e?.error?.message||'CSV import failed. Existing data was not changed.')});};reader.readAsText(file);}
 private error(text:string){this.message.set({kind:'error',text});} private empty():ETFMasterPayload{return{symbol:'',underlying:'',securityName:'',dateOfListing:'',marketLot:1,isinNumber:'',faceValue:0};}
}
